---
- name: Deploy dotfiles
  hosts: all
  gather_facts: true
  vars:
    dotfiles_dir: "{{ playbook_dir }}"
    home_dir: "{{ ansible_env.HOME }}"

  pre_tasks:
    - name: Ensure required directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ home_dir }}/.config"

  roles:
    - ghostty
    - git
    - ssh
    - tmux
    - vim
    - zsh

  post_tasks:
    - name: Display completion message
      ansible.builtin.debug:
        msg: "Dotfiles have been successfully deployed to {{ home_dir }}"
