---
- name: Apply macOS defaults
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  loop: "{{ macos_defaults }}"
  notify:
    - Restart Dock
    - Restart Finder
  tags: macos
