---
- name: Ensure SSH directory exists
  ansible.builtin.file:
    path: "{{ home_dir }}/.ssh"
    state: directory
    mode: '0755'
  tags: ssh

- name: Copy SSH configuration
  ansible.builtin.copy:
    src: config
    dest: "{{ home_dir }}/.ssh/config"
    mode: '0600'
  tags: ssh
