---
- name: Ensure ghostty config directory exists
  ansible.builtin.file:
    path: "{{ home_dir }}/.config/ghostty"
    state: directory
    mode: '0755'
  tags: ghostty

- name: Remove existing ghostty application support directory
  ansible.builtin.file:
    path: "{{ home_dir }}/Library/Application Support/com.mitchellh.ghostty"
    state: absent
  when: ansible_system == "Darwin"
  tags: ghostty

- name: Copy ghostty configuration
  ansible.builtin.copy:
    src: config
    dest: "{{ home_dir }}/.config/ghostty/config"
    backup: true
    mode: '0644'
  tags: ghostty
